package io.opentelemetry.contrib.auto.annotations;

/**
 * This class is not a classical test. It's just a demonstration of possible usages of {@link
 * WithSpan} annotation together with some explanations. The goal of this class is to serve as an
 * early detection system for inconvenient API and unintended API breakage.
 */
@SuppressWarnings("unused")
public class WithSpanUsageExamples {

  /**
   * A new span will be created for this method's execution. Span's name will be automatically
   * generated by OpenTelemetry auto-instrumentation, probably as "WithSpanUsageExamples.method1".
   */
  @WithSpan
  public void method1() {}

  /** Name of the generated span will be "shinyName" */
  @WithSpan("shinyName")
  public void method2() {}
}
