version: 2
registries:
  gradle-plugin-portal:
    type: maven-repository
    url: https://plugins.gradle.org/m2
    username: dummy # Required by dependabot
    password: dummy # Required by dependabot
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/"
    registries:
      - gradle-plugin-portal
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "edu.berkeley.cs.jqf:jqf-fuzz"
      - dependency-name: "org.jetbrains.kotlinx:kotlinx-coroutines-core"
      # Ignore updates to next mockito major version 5.x.x, which requires Java 11
      - dependency-name: "org.mockito:mockito-core"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.junit-pioneer:junit-pioneer"
        # junit-pioneer 2.x requires Java 11
        versions: [ "[1,)" ]
