codecov:
  notify:
    require_ci_to_pass: yes
  strict_yaml_branch: main  # only use the latest copy on main branch
  max_report_age: off

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: 89%
        paths:
          - "!opencensus-shim/"
          - "!opentracing-shim/"
      unmaintained:
        target: 80%
        paths:
          - "opencensus-shim/"
          - "opentracing-shim/"
    patch:
      default:
        target: 80%
