timeout = 30
retry_wait_time = 10
max_retries = 6
max_concurrency = 4

# Check fragments in links
include_fragments = true

# excluding links to pull requests and issues is done for performance
exclude = [
  "^https://github.com/open-telemetry/opentelemetry-java/(issues|pull)/\\d+$",
  '^https://central.sonatype.com/service/rest/repository/browse/maven-snapshots/io/opentelemetry/$',
]


