[tools]

# Linters
"github:grafana/flint" = "0.21.0"
lychee = "0.23.0"

[tasks.lint]
description = "Run link checks"
raw_args = true
run = "flint run"

[tasks."lint:fix"]
description = "Auto-fix lint issues"
run = "flint run --fix"

[env]
FLINT_CONFIG_DIR = ".github/config"
