package io.opentelemetry.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.plugins.JavaPlugin
import org.gradle.api.plugins.JavaPluginExtension
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import org.gradle.kotlin.dsl.the
import java.io.File

/**
 * This gradle plugin will define a new task called generateOtelVersionClass.
 * This task generates a Java source file that contains the project version
 * as a string constant. The "compileJava" task is updated to depend on
 * generateOtelVersionClass, and the project source set is updated to
 * include the new file.
 */
class OtelVersionClassPlugin : Plugin<Project> {
  override fun apply(project: Project) {
    project.plugins.apply(JavaPlugin::class.java)

    val outDir = project.layout.buildDirectory.dir("generated/sources/version/java/main")

    project.tasks.register("generateOtelVersionClass", GenerateOtelVersionClassTask::class.java) {
      projectGroup.set("${project.group}")
      projectName.set(project.name)
      projectVersion.set("${project.version}")
      outputDirectory.set(outDir)
    }
    // Add dependency on this task
    project.tasks.matching { it.name == "compileJava" || it.name == "sourcesJar" }.configureEach {
      dependsOn("generateOtelVersionClass")
    }
    // Add new source dir to the "main" source set
    val java = project.the<JavaPluginExtension>()
    java.sourceSets.getByName("main").java {
      srcDir(outDir)
    }
  }
}

abstract class GenerateOtelVersionClassTask : DefaultTask() {
  @get:Input
  abstract val projectGroup: Property<String>

  @get:Input
  abstract val projectName: Property<String>

  @get:Input
  abstract val projectVersion: Property<String>

  @get:OutputDirectory
  abstract val outputDirectory: DirectoryProperty

  @TaskAction
  fun generate() {
    val group = projectGroup.get().replace('.', '/')
    val name = projectName.get().replace('-', '/')
    val outDir = outputDirectory.get().asFile
    val filename = "$group/$name/internal/OtelVersion.java"
    val outFile = File(outDir, filename)
    val packageName = "${projectGroup.get()}.${projectName.get().replace('-', '.')}.internal"
    val classBody = getClassBody(projectVersion.get(), packageName)

    outFile.parentFile.mkdirs()
    outFile.writeText(classBody)
  }

  private fun getClassBody(version: String, packageName: String): String {
    return """
      package $packageName;
      
      import javax.annotation.Generated;
      
      /** Autogenerated class do not edit. */
      @Generated("io.opentelemetry.gradle.OtelVersionClassPlugin")
      public final class OtelVersion {
        public static final String VERSION = "$version";

        private OtelVersion() {}
      }
    """.trimIndent()
  }
}
