/*
 * Copyright 2019, OpenTelemetry Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.opentelemetry.contrib.http.servlet;

import static com.google.common.base.Strings.isNullOrEmpty;
import static com.google.common.base.Strings.lenientFormat;

import com.google.common.base.Splitter;
import java.util.List;
import javax.annotation.Nullable;
import javax.servlet.http.HttpServletRequest;

/** Extracts AWS X-Ray header values. */
public class AwxXrayHttpPropagationGetter extends BaseSchemeSpecificHttpPropagationGetter {

  /** Unique id of this scheme-specific getter. */
  public static final String SCHEME_NAME = "awsXRay";
  /** AWS X-Ray tracing id header generated by API Gateway and ALBs. */
  public static final String XAMZNTRACEID = "X-Amzn-Trace-Id";
  /** AWS request id header generated by API Gateway and CloudFront. */
  public static final String XAMZNREQUESTID = "x-amzn-RequestId";
  /** Tracestate key for AWS request id. */
  public static final String AMZNREQUESTIDKEY = "amznReqId";

  private static final String XRAY_PREFIX_ROOT = "Root=";
  private static final String XRAY_PREFIX_PARENT = "Parent=";
  private static final String XRAY_PREFIX_SAMPLED = "Sampled=";
  private static final String XRAY_PREFIX_SELF = "Self=";
  private static final String XRAY_SAMPLED_VAL = "1";
  private static final char XRAY_SEPARATOR = '-';
  private static final int XRAY_TRACE_LEN = 35;
  private static final int XRAY_SPAN_LEN = 16;
  private static final String XRAY_DEFAULT_SPAN = "0000000000000004";
  private static final String TRACE_FLAGS_DEFAULT = "00";
  private static final String TRACE_FLAGS_SAMPLED = "01";
  private static final String W3C_VERSION = "00";
  private static final char W3C_SEPARATOR = '-';

  /** Constructs a getter object. */
  public AwxXrayHttpPropagationGetter() {
    super(SCHEME_NAME);
  }

  @Override
  public boolean canProvideValues(HttpServletRequest request) {
    return request.getHeader(XAMZNTRACEID) != null;
  }

  @Nullable
  @Override
  protected String extractAndConstructTraceparentHeaderValue(HttpServletRequest request) {
    String xraytraceid = request.getHeader(XAMZNTRACEID);
    if (isNullOrEmpty(xraytraceid)) {
      return null;
    }
    String traceId = null;
    String spanId = null;
    String spanIdFromSelf = null;
    String traceFlags = TRACE_FLAGS_DEFAULT;
    List<String> parts = Splitter.on(';').splitToList(xraytraceid);
    for (String part : parts) {
      if (part.startsWith(XRAY_PREFIX_ROOT)) {
        traceId =
            convertRoot2TraceId(part.substring(XRAY_PREFIX_ROOT.length()).toLowerCase().trim());
      } else if (part.startsWith(XRAY_PREFIX_PARENT)) {
        spanId =
            convertParent2SpanId(part.substring(XRAY_PREFIX_PARENT.length()).toLowerCase().trim());
      } else if (part.startsWith(XRAY_PREFIX_SELF)) {
        spanIdFromSelf =
            convertSelf2SpanId(part.substring(XRAY_PREFIX_SELF.length()).toLowerCase().trim());
      } else if (part.startsWith(XRAY_PREFIX_SAMPLED)) {
        traceFlags =
            convertSampled2TraceFlags(
                part.substring(XRAY_PREFIX_SAMPLED.length()).toLowerCase().trim());
      }
    }
    if (traceId == null) {
      throw new IllegalArgumentException(
          lenientFormat("Invalid AWS X-Ray Trace Id: %s", xraytraceid));
    }
    if (spanId == null) {
      if (spanIdFromSelf == null) {
        spanId = XRAY_DEFAULT_SPAN;
      } else {
        spanId = spanIdFromSelf;
      }
    }
    return new StringBuilder()
        .append(W3C_VERSION)
        .append(W3C_SEPARATOR)
        .append(traceId)
        .append(W3C_SEPARATOR)
        .append(spanId)
        .append(W3C_SEPARATOR)
        .append(traceFlags)
        .toString();
  }

  @Nullable
  @Override
  protected String extractAndConstructTracestateHeaderValue(HttpServletRequest request) {
    String awsRequestId = request.getHeader(XAMZNREQUESTID);
    if (isNullOrEmpty(awsRequestId)) {
      return null;
    }
    return new StringBuilder()
        .append(AMZNREQUESTIDKEY)
        .append('=')
        .append(awsRequestId.toLowerCase())
        .toString();
  }

  private static String convertRoot2TraceId(String amznId) {
    if (amznId.length() != XRAY_TRACE_LEN
        || amznId.charAt(1) != XRAY_SEPARATOR
        || amznId.charAt(10) != XRAY_SEPARATOR) {
      throw new IllegalArgumentException(lenientFormat("Invalid AWS X-Ray Root ID: %s", amznId));
    }
    return amznId.substring(2, 10) + amznId.substring(11);
  }

  private static String convertParent2SpanId(String amznId) {
    if (amznId.length() != XRAY_SPAN_LEN) {
      throw new IllegalArgumentException(lenientFormat("Invalid AWS X-Ray Segment ID: %s", amznId));
    }
    return amznId;
  }

  private static String convertSelf2SpanId(String amznId) {
    if (amznId.length() != XRAY_TRACE_LEN
        || amznId.charAt(1) != XRAY_SEPARATOR
        || amznId.charAt(10) != XRAY_SEPARATOR) {
      throw new IllegalArgumentException(lenientFormat("Invalid AWS X-Ray Self ID: %s", amznId));
    }
    return amznId.substring(11, 27);
  }

  private static String convertSampled2TraceFlags(String amznId) {
    return XRAY_SAMPLED_VAL.equals(amznId) ? TRACE_FLAGS_SAMPLED : TRACE_FLAGS_DEFAULT;
  }
}
