/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

package io.opentelemetry.exporter.sender.okhttp.internal;

import java.io.IOException;
import okhttp3.Interceptor;
import okhttp3.Response;
import org.jetbrains.annotations.NotNull;

/**
 * Unwrapper of IOExceptions generated by the OkHttp requests.
 *
 * <p>This class is internal and is hence not for public use. Its APIs are unstable and can change
 * at any time.
 */
public class IOeExceptionInterceptor implements Interceptor {
  @NotNull
  @Override
  public Response intercept(@NotNull Chain chain) throws IOException {
    try {
      return chain.proceed(chain.request());
    } catch (Throwable e) {
      Throwable exceptionCause = e.getCause();
      if (exceptionCause instanceof IOException) {
        throw (IOException) exceptionCause;
      }
      throw e;
    }
  }
}
