/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

package io.opentelemetry.sdk.metrics.view;

import io.opentelemetry.sdk.metrics.aggregator.AggregatorFactory;
import io.opentelemetry.sdk.metrics.processor.LabelsProcessorFactory;

public final class ViewBuilder {
  private AggregatorFactory aggregatorFactory;
  private LabelsProcessorFactory labelsProcessorFactory = LabelsProcessorFactory.noop();

  ViewBuilder() {}

  /**
   * Sets the name of the View.
   *
   * <p>Metrics generated by this view will use this name instead of the underlying instrument name.
   */
  public ViewBuilder setName(String name) {
    // TODO: Implement
    return this;
  }

  /**
   * Sets the description of the View.
   *
   * <p>Metrics generated by this view will use this description instead of the underlying
   * instrument description.
   */
  public ViewBuilder setDescription(String description) {
    // TODO: Implement
    return this;
  }

  // TODO: set aggregation
  // TODO: set attribute key (filter)
  // TODO: set extra dimensions (baggage)

  /**
   * sets {@link AggregatorFactory}.
   *
   * @param aggregatorFactory aggregator factory.
   * @return this Builder.
   */
  public ViewBuilder setAggregatorFactory(AggregatorFactory aggregatorFactory) {
    this.aggregatorFactory = aggregatorFactory;
    return this;
  }

  /**
   * sets {@link LabelsProcessorFactory}.
   *
   * @param labelsProcessorFactory labels processor factory.
   * @return this Builder.
   */
  public ViewBuilder setLabelsProcessorFactory(LabelsProcessorFactory labelsProcessorFactory) {
    this.labelsProcessorFactory = labelsProcessorFactory;
    return this;
  }

  public View build() {
    return View.create(this.aggregatorFactory, this.labelsProcessorFactory);
  }
}
