/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

package io.opentelemetry.sdk.trace;

import io.opentelemetry.api.trace.SpanId;
import io.opentelemetry.api.trace.TraceId;
import javax.annotation.concurrent.ThreadSafe;

/** Interface used by the {@link SdkTracer} to generate new {@link SpanId}s and {@link TraceId}s. */
@ThreadSafe
public interface IdGenerator {

  /**
   * Returns a {@link IdGenerator} that generates purely random IDs, which is the default for
   * OpenTelemetry.
   *
   * <p>The underlying implementation uses {@link java.util.concurrent.ThreadLocalRandom} for
   * randomness but may change in the future.
   */
  static IdGenerator random() {
    // note: uses RandomHolder's platformDefault to account for android.
    return RandomIdGenerator.INSTANCE;
  }

  /**
   * Generates a new valid {@code SpanId}.
   *
   * @return a new valid {@code SpanId}.
   */
  String generateSpanId();

  /**
   * Generates a new valid {@code TraceId}.
   *
   * @return a new valid {@code TraceId}.
   */
  String generateTraceId();

  /**
   * Declares whether TraceIds generated by this IdGenerator have their lower 56 bits uniformly
   * distributed over the [0..2^56-1]interval, making them compatible with W3C Trace Context Level 2
   * recommendation @see <a href=
   * "https://www.w3.org/TR/trace-context-2/#random-trace-id-flag">Random TraceId flag</a>.
   *
   * @return true if the generated TraceIds are random
   */
  default boolean generatesRandomTraceIds() {
    return false;
  }
}
