name: Benchmark Main

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sdk-benchmark:
    if: github.repository == 'open-telemetry/opentelemetry-java'
    permissions:
      contents: write # for git push to benchmarks branch
    name: Benchmark SDK
    runs-on: oracle-bare-metal-64cpu-1024gb-x86-64-ubuntu-24
    container:
      image: ubuntu:26.04@sha256:b7f48194d4d8b763a478a621cdc81c27be222ba2206ca3ca6bc42b49685f3d9e
    timeout-minutes: 120 # since there is only a single bare metal runner across all repos
    steps:
      - name: Install Git
        run: |
          apt-get update
          apt-get install -y git

      - name: Configure Git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - id: setup-java
        name: Set up Java for build
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          distribution: temurin
          java-version: 21

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
      - name: Run jmh
        run: ./gradlew jmhJar
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

      # TODO (jack-berg): Select or build appropriate benchmarks for other key areas:
      # - Log SDK export
      # - Trace SDK export
      # - Metric SDK export
      # - Noop implementation
      - name: Run Benchmark
        run: |
          cd sdk/all/build
          java -jar libs/opentelemetry-sdk-*-jmh.jar -rf json MetricRecordBenchmark SpanRecordBenchmark LogRecordBenchmark

      - name: Use CLA approved github bot
        run: .github/scripts/use-cla-approved-bot.sh

      - name: Store benchmark results
        uses: benchmark-action/github-action-benchmark@52576c92bccf6ac60c8223ec7eb2565637cae9ba # v1.22.1
        with:
          tool: 'jmh'
          output-file-path: sdk/all/build/jmh-result.json
          gh-pages-branch: benchmarks
          github-token: ${{ secrets.GITHUB_TOKEN }}
          benchmark-data-dir-path: "benchmarks"
          auto-push: true

  workflow-notification:
    permissions:
      issues: write
    needs:
      - sdk-benchmark
    if: always()
    uses: open-telemetry/shared-workflows/.github/workflows/workflow-failure-issue.yml@62d5939b47144252763c5ff9fffe8c20d76cd806 # v0.4.0
    with:
      success: ${{ needs.sdk-benchmark.result == 'success' }}
