name: Benchmark Main

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sdk-benchmark:
    if: github.repository == 'open-telemetry/opentelemetry-java'
    permissions:
      contents: write # for git push to benchmarks branch
    name: Benchmark SDK
    runs-on: oracle-bare-metal-64cpu-1024gb-x86-64-ubuntu-24
    container:
      image: ubuntu:26.04@sha256:513c074113a871b51a8d16ab445c88779d6452d937a164fb5cc479f32668a41d
    timeout-minutes: 120 # since there is only a single bare metal runner across all repos
    steps:
      - name: Install Git
        run: |
          apt-get update
          apt-get install -y git

      - name: Configure Git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - id: setup-java
        name: Set up Java for build
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: temurin
          java-version: 25

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
        with:
          cache-read-only: true
      - name: Run jmh
        run: ./gradlew jmhJar
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

      # TODO (jack-berg): Select or build appropriate benchmarks for other key areas:
      # - Log SDK export
      # - Trace SDK export
      # - Metric SDK export
      # - Noop implementation
      - name: Run Benchmark
        run: |
          cd sdk/all/build
          java -jar libs/opentelemetry-sdk-*-jmh.jar -rf json MetricRecordBenchmark SpanRecordBenchmark LogRecordBenchmark

      - name: Use CLA approved github bot
        run: .github/scripts/use-cla-approved-bot.sh

      - name: Store benchmark results
        uses: benchmark-action/github-action-benchmark@4322e5726e6334590d251fc4f92bec0efafc45dc # v1.22.2
        with:
          tool: 'jmh'
          output-file-path: sdk/all/build/jmh-result.json
          gh-pages-branch: benchmarks
          github-token: ${{ secrets.GITHUB_TOKEN }}
          benchmark-data-dir-path: "benchmarks"
          auto-push: true

  workflow-notification:
    permissions:
      issues: write
    needs:
      - sdk-benchmark
    if: always()
    uses: open-telemetry/shared-workflows/.github/workflows/workflow-failure-issue.yml@68c7b2f0ef9cd9c1e2b71d3018f63127be189578 # v0.14.0
    with:
      success: ${{ needs.sdk-benchmark.result == 'success' }}
