name: Build (daily)

on:
  schedule:
    # daily at 3:24 UTC
    - cron: "24 3 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  link-check:
    uses: ./.github/workflows/reusable-link-check.yml

  publish-snapshots:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version: 21

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
        with:
          # use basic cache provider which has a more permissive MIT license
          # see https://github.com/gradle/actions/releases/tag/v6.1.0
          cache-provider: basic

      - name: Publish to Sonatype
        run: ./gradlew assemble publishToSonatype
        env:
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_KEY: ${{ secrets.SONATYPE_KEY }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          # disable gradle build cache, ensuring we're building from source to mitigate supply chain risk
          DISABLE_REMOTE_BUILD_CACHE: true

  workflow-notification:
    permissions:
      contents: read
      issues: write
    needs:
      - link-check
      - publish-snapshots
    if: always()
    uses: ./.github/workflows/reusable-workflow-notification.yml
    with:
      success: >-
        ${{
          needs.link-check.result == 'success' &&
          needs.publish-snapshots.result == 'success'
        }}
