name: Build tracecontext testsuite

on:
  push:
    paths:
      - 'integration-tests/tracecontext/docker/**'
      - '.github/workflows/build-tracecontext-testsuite.yaml'
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Login to GitHub package registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: integration-tests/tracecontext/docker
          push: true
          tags: ghcr.io/open-telemetry/java-test-containers:w3c-tracecontext-testsuite
