name: Build (daily)

on:
  schedule:
    # daily at 3:24 UTC
    - cron: "24 3 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  link-check:
    if: github.repository == 'open-telemetry/opentelemetry-java'
    uses: ./.github/workflows/reusable-link-check.yml

  publish-snapshots:
    if: github.repository == 'open-telemetry/opentelemetry-java'
    environment: protected
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Java
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          distribution: temurin
          java-version: 21

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: Publish to Sonatype
        run: ./gradlew assemble publishToSonatype
        env:
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_KEY: ${{ secrets.SONATYPE_KEY }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          # disable gradle build cache, ensuring we're building from source to mitigate supply chain risk
          DISABLE_REMOTE_BUILD_CACHE: true

  workflow-notification:
    permissions:
      issues: write
    needs:
      - link-check
      - publish-snapshots
    if: always()
    uses: open-telemetry/shared-workflows/.github/workflows/workflow-failure-issue.yml@62d5939b47144252763c5ff9fffe8c20d76cd806 # v0.4.0
    with:
      success: >-
        ${{
          needs.link-check.result == 'success' &&
          needs.publish-snapshots.result == 'success'
        }}
