name: FOSSA

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  fossa:
    if: github.repository == 'open-telemetry/opentelemetry-java'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: fossas/fossa-action@29693cc50323968e039056be419b32989fc5880c # v2.0.0
        with:
          api-key: ${{secrets.FOSSA_API_KEY}}
          team: OpenTelemetry

  workflow-notification:
    permissions:
      issues: write
    needs:
      - fossa
    if: always()
    uses: open-telemetry/shared-workflows/.github/workflows/workflow-failure-issue.yml@62d5939b47144252763c5ff9fffe8c20d76cd806 # v0.4.0
    with:
      success: ${{ needs.fossa.result == 'success' }}
