name: OSSF Scorecard

on:
  push:
    branches:
      - main
  schedule:
    - cron: "43 6 * * 5" # weekly at 06:43 (UTC) on Friday
  workflow_dispatch:

permissions: {}

jobs:
  analysis:
    if: github.repository == 'open-telemetry/opentelemetry-java'
    permissions:
      contents: read # for actions/checkout
      id-token: write # for Scorecard to publish results
      security-events: write # for the SARIF upload to code scanning
    uses: open-telemetry/shared-workflows/.github/workflows/scorecard.yml@f13d0cb656d7244ca8c1638b6996dbaef1083bdd # v0.6.0

  workflow-notification:
    permissions:
      issues: write
    needs:
      - analysis
    if: always()
    uses: open-telemetry/shared-workflows/.github/workflows/workflow-failure-issue.yml@62d5939b47144252763c5ff9fffe8c20d76cd806 # v0.4.0
    with:
      success: ${{ needs.analysis.result == 'success' }}
