name: Update gradle wrappers (daily)

on:
  schedule:
    # daily at 1:30 UTC
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: setup-java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1

  workflow-notification:
    needs:
      - update-gradle-wrapper
    if: always()
    uses: ./.github/workflows/reusable-workflow-notification.yml
    with:
      success: ${{ needs.update-gradle-wrapper.result == 'success' }}
